import { ChuDauTuEntity } from '@shared/interfaces/chu-dau-tu.interface';
import { DiaChiEntity } from '@shared/interfaces/dia-chi.interface';
import { DoAnEntity } from '@shared/interfaces/do-an.interface';
import { LoaiCongTrinhCPXDEntity } from '@shared/services/cong-trinh-xay-dung/cap-phep-xay-dung/loai-cong-trinh/loai-cong-trinh.interface';
import { LoaiVonCongTrinhCPXDEntity } from '@shared/services/cong-trinh-xay-dung/cap-phep-xay-dung/loai-von-cong-trinh.interface';
import { CapCongTrinhEntity } from '@shared/services/cong-trinh-xay-dung/cong-trinh-xay-dung.interface';
import { CongTrinhXayDungEntity } from '@shared/services/cong-trinh-xay-dung/cong-trinh-xd/cong-trinh-xay-dung.interface';
import { LoaiCongTrinhEntity } from '../../loai-cong-trinh-xay-dung.interface';
import { LoaiHinhCongViecThamDinhEntity } from '../../tham-dinh-co-so/loai-hinh-cong-viec/loai-hinh-cong-viec.interface';
import { ChiTietDonViThietKeCongTrinhTDXDEntity } from '../chi-tiet-dv/chi-tiet-dv.interface';
import { ChiTieuThietKeTDXDEntity } from '../chi-tieu-thiet-ke/chi-tieu-thiet-ke.interface';
import { HoatDongTDXDEntity } from '../hoat-dong/hoat-dong.interface';
import { LichSuTienDoTDXDEntity } from '../lich-su-tien-do/lich-su-tien-do.interface';
import { ThoiGianHetHanTDXDEntity } from '../thoi-gian-het-han/thoi-gian-het-han.interface';
import { TienDoTDXDEntity } from '../tien-do/tien-do.interface';
import { TinhTrangChuyenModuleTDXDEntity } from '../tinh-trang-chuyen-module/tinh-trang-chuyen-module.interface';
import { TinhTrangTraHoSoTDXDEntity } from '../tinh-trang-tra-ho-so/tinh-trang-tra-ho-so.interface';
import { VanBanTDXDEntity } from '../van-ban/van-ban.interface';

export interface ThongTinCongTrinhTDXDEntity {
  maCTTDXD: string;
  maCTCha?: string;
  congTrinhCha?: ThongTinCongTrinhTDXDEntity;
  maCTXD: string;
  tinhTrangTraHoSo: Partial<TinhTrangTraHoSoTDXDEntity>;
  tinhTrangChuyenModule: TinhTrangChuyenModuleTDXDEntity;
  congTrinhXayDung: Partial<CongTrinhXayDungEntity>;
  maHoSo: string;
  maLoaiHinhCongViecTD?: number;
  loaiHinhCongViecTD?: LoaiHinhCongViecThamDinhEntity;
  chiTieuThietKe: ChiTieuThietKeTDXDEntity;
  soTo: string;
  soThua: string;
  diaChi: DiaChiEntity;
  dienTich: number;
  tenCongTrinh: string;
  maTienDo: string;
  tienDo: TienDoTDXDEntity;
  maChuDauTu: string;
  chuDauTu: ChuDauTuEntity;
  maVonCongTrinh: number;
  vonCongTrinh: LoaiVonCongTrinhCPXDEntity;
  giaTriDuToan: string;
  tgHetHan: ThoiGianHetHanTDXDEntity;
  maLoaiCongTrinh: string;
  loaiCongTrinh: LoaiCongTrinhCPXDEntity;
  maCapCongTrinh: number;
  capCongTrinh: CapCongTrinhEntity;
  giaTriTongMucDauTu?: string;
  maLoaiCTTKKT?: string;
  loaiCTTKKT?: LoaiCongTrinhEntity;
  maDoAn: string;
  doAn: DoAnEntity;
  tcqc: string;
  thongTinKhac: string;
  donVis: Partial<ChiTietDonViThietKeCongTrinhTDXDEntity>[];
  lichSuTienDos: LichSuTienDoTDXDEntity[];
  hoatDongs: HoatDongTDXDEntity[];
  vanBans: VanBanTDXDEntity[];
  shape: any;
}
